FROM python:BASE_PY_VERSION-jessie

ENV LANG C.UTF-8
# For Dojo:
# * entrypoint requires sudo and shadow
# * git is needed to install dojo image configs
# * ca-certificated needed when running git clone
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends sudo git ca-certificates && \
  git clone --depth 1 -b 0.2.1 https://github.com/ai-traders/dojo.git /tmp/dojo_git &&\
  /tmp/dojo_git/image_scripts/src/install.sh && \
  rm -r /tmp/dojo_git && \
  echo 'dojo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

COPY apt_01proxy /etc/apt/apt.conf.d/01_proxy

COPY ./ca.crt /usr/local/share/ca-certificates/ait.crt
RUN update-ca-certificates

# * software-properties-common - to make add-apt-repository work
# * ssh-client - to run git clone over ssh
# * locale-gen en_US.UTF-8 - so that perl does not complain like: "perl: warning: Setting locale failed."
RUN apt-get update &&\
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  locales &&\
  echo 'LANG="en_US.UTF-8"'>/etc/default/locale &&\
  locale-gen en_US.UTF-8 &&\
  update-locale LANG=C.UTF-8 &&\
  dpkg-reconfigure --frontend=noninteractive locales  &&\
  DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
  wget curl \
  ssh-client build-essential
RUN pip install virtualenv tox
COPY virtualenvs_requirements /tmp/virtualenvs_requirements
RUN cd /tmp/virtualenvs_requirements/locust &&\
  virtualenv /dojo/virtualenvs/locust &&\
  . /dojo/virtualenvs/locust/bin/activate &&\
  pip install -r requirements.txt
RUN chown dojo:dojo -R /dojo/virtualenvs

RUN pip install devpi-client==3.0.0
# ensure pretty bash prompt
COPY bashrc /home/dojo/.bashrc
COPY profile /home/dojo/.profile
RUN chown dojo:dojo -R /home/dojo

COPY etc_dojo.d/scripts/* /etc/dojo.d/scripts/

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
CMD ["/bin/bash"]

ARG this_image_tag_arg
ARG this_image_name_arg
ENV this_image_tag=${this_image_tag_arg} this_image_name=${this_image_name_arg}
